@startuml
skinparam classAttributeIconSize 0
interface BancoDeDados { +descricao(): String }
interface Cache { +descricao(): String }
interface Logger { +descricao(): String }
class BancoH2
class BancoPostgres
class CacheMemoria
class CacheRedis
class LoggerConsole
class LoggerNuvem
interface AmbienteFactory {
  +criarBanco(): BancoDeDados
  +criarCache(): Cache
  +criarLogger(): Logger
  +nome(): String
}
class AmbienteDesenvolvimentoFactory
class AmbienteProducaoFactory
class Deploy {
  -ambiente: String
  +Deploy(fabrica: AmbienteFactory)
  +executar()
}
BancoDeDados <|.. BancoH2
BancoDeDados <|.. BancoPostgres
Cache <|.. CacheMemoria
Cache <|.. CacheRedis
Logger <|.. LoggerConsole
Logger <|.. LoggerNuvem
AmbienteFactory <|.. AmbienteDesenvolvimentoFactory
AmbienteFactory <|.. AmbienteProducaoFactory
AmbienteDesenvolvimentoFactory ..> BancoH2 : cria
AmbienteDesenvolvimentoFactory ..> CacheMemoria : cria
AmbienteDesenvolvimentoFactory ..> LoggerConsole : cria
AmbienteProducaoFactory ..> BancoPostgres : cria
AmbienteProducaoFactory ..> CacheRedis : cria
AmbienteProducaoFactory ..> LoggerNuvem : cria
Deploy --> AmbienteFactory
Deploy --> BancoDeDados
Deploy --> Cache
Deploy --> Logger
@enduml
